-- ==========================================================
-- Supabase Schema for Blog Posts Manager
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
-- ==========================================================

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    email TEXT,
    bio TEXT,
    avatar_url TEXT,
    website TEXT,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Posts Table
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    cover_image TEXT,
    category TEXT DEFAULT 'General',
    author_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL DEFAULT 'Anonymous',
    author_avatar TEXT,
    read_time TEXT DEFAULT '3 min read',
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    shares_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    author_id TEXT REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL DEFAULT 'Reader',
    author_avatar TEXT,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Likes Table
CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(post_id, user_id)
);

-- 5. Shares Table
CREATE TABLE IF NOT EXISTS public.shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    platform TEXT DEFAULT 'link',
    user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_likes_post_id ON public.likes(post_id);
CREATE INDEX IF NOT EXISTS idx_shares_post_id ON public.shares(post_id);

-- 7. Seed Initial Data
INSERT INTO public.profiles (id, username, display_name, email, bio, avatar_url, website, location)
VALUES 
    ('user_admin', 'faruk_dev', 'Faruk Developer', 'faruk@example.com', 'DevOps engineer & full-stack architect building modern web products.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', 'https://github.com/Faruk1350', 'San Francisco, CA'),
    ('user_sarah', 'sarah_design', 'Sarah Chen', 'sarah@example.com', 'Product designer & minimalist enthusiast. Writing about UX, design systems, and craft.', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', 'https://sarahchen.design', 'Toronto, ON')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.posts (title, content, cover_image, category, author_id, author_name, author_avatar, read_time, likes_count, comments_count, shares_count)
VALUES 
    (
        'Building Minimalist Interfaces with Modern Web Tools',
        'Minimalism in user interface design is not merely the absence of clutter; it is the deliberate elevation of what truly matters. When every element on a page serves an intentional purpose, cognitive load drops and delight surges.\n\nIn this article, we explore how clean typography, deliberate whitespace, and soft light palettes create timeless digital experiences.',
        'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1200&auto=format&fit=crop&q=80',
        'Design',
        'user_sarah',
        'Sarah Chen',
        'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        '4 min read',
        18,
        2,
        6
    ),
    (
        'From Flask to FastAPI: Why Asynchronous Python Matters',
        'FastAPI has redefined the Python backend ecosystem. With native type hints via Pydantic, automatic OpenAPI documentation, and blistering ASGI performance via Starlette and Uvicorn, transitioning from traditional WSGI frameworks feels like a generational leap forward.\n\nHere is how we redesigned our services for high-throughput concurrency and clean developer ergonomics.',
        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80',
        'Engineering',
        'user_admin',
        'Faruk Developer',
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        '5 min read',
        24,
        1,
        12
    ),
    (
        'Supercharging Realtime Apps with Supabase PostgreSQL',
        'Supabase provides developers with an enterprise-grade Postgres database coupled with instant REST, GraphQL, realtime subscriptions, authentication, and vector embeddings.\n\nLearn how adopting a robust database-first mindset transforms your application architecture and scales effortlessly.',
        'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80',
        'Database',
        'user_admin',
        'Faruk Developer',
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        '3 min read',
        31,
        2,
        9
    )
ON CONFLICT DO NOTHING;

INSERT INTO public.comments (post_id, author_id, author_name, author_avatar, content)
VALUES
    (1, 'user_admin', 'Faruk Developer', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', 'The subtle lighting and whitespace tips made a huge difference in our product readability!'),
    (1, 'user_sarah', 'Sarah Chen', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', 'Glad you enjoyed it! Minimal design allows typography to do the heavy lifting.'),
    (2, 'user_sarah', 'Sarah Chen', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', 'FastAPI automatic Swagger docs are such a joy to work with on the frontend team!'),
    (3, 'user_sarah', 'Sarah Chen', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', 'Postgres row-level security is a game changer.');
